language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  app:
    secure: ZwKQ+lO2+dqd6F/mEAhap5/RgghjDoHLNJHSsRLU7O7Xh43re/39HH4K+cYggXK/esjzyphyp/sbKoRebragfBRONOzH7GhvAoMM39NXKgWGeO76qre7Bc+mYnUjU7iLBUa7/TZvdYSJ9LrVKDkPwJH3QlhVjdrAQ62D9TWRKs0=
  api_key:
    secure: U3ZysEmg+ksknox7eHsDw16rhUDY7Nn55BpOS5IojMDwGW8xCQN9o7L9zAfgZMdPXWUGwV1N5QTwke/JdLd/n9YDgxHmz1BWsMW5CfbuCLQjzV4jK7iDvgiBXBTf3U7llLe0x6p2rTOAFVmGOKNeUhcpOfqsjIdyDT4VjPKW8sQ=
