language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: eeCvwqGJdHQMd5pCZaNjdNVUE5KbsRwJrYtpUwjXc/vujEdCwuCBSFsZVADjYBD8SrkBKR17ebAgW86IZ60HGv3yKd4VVoPGL0Wv8h1CYT7YNx1EHwUNx/hkfeE3ApWQE+Q5LjRAUtlC5NNqplxgzB4EOLj/XultLwE2Nsd34h4=
  app:
    secure: YzIM0R+HUF9XnSty/P/oIYLtu6ZQm6X8YAaU8FmXV626AlHOU+IUukX3S0An4ukuBooPeBv4hwMxRuSpvKJ58oFaTzoycdTYI9Vgb/1x9kRloqjHRxQd49AkQ6384TePSR8d6Ee+F9vA4AREgAE3TpBsYegLP2OlF767r+i6Aik=
