language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: "RjEcX1RDDw2PaaQlQiz0M5E7F1QH8lOPkuvVP8UDBsi7ZxHJP5Hq0P0TwGJ9Xd25mE6b6vk3sw8q9mONLvgLizuu3fPoNU0aBfDtnjVb6jUilL91BDMF/47k5eMNQUGjS8VBoC+6jJhqQWAso2unhDc2NZpd6RV8dsRu9u7v3LY="
  app:
    secure: "YzIM0R+HUF9XnSty/P/oIYLtu6ZQm6X8YAaU8FmXV626AlHOU+IUukX3S0An4ukuBooPeBv4hwMxRuSpvKJ58oFaTzoycdTYI9Vgb/1x9kRloqjHRxQd49AkQ6384TePSR8d6Ee+F9vA4AREgAE3TpBsYegLP2OlF767r+i6Aik="
