language: node_js
node_js:
- "8"
deploy:
  provider: heroku
  api_key:
    secure: "HEojdsn7+/hgeRjv6ZdhFoPOmowEAwOXJtl4WMBHBln8xQAh3Jtmqh6OlYsBjjP6/vNSViR66AK0DZ3AA3+iPAiRCnieGzR+tVv8FD7sKXcmSU7uAL2pMHS1OHIcNimzPgzPj6DVWdWtC7nVLVMOJnOYksdpjhO5M60ih7ms6Ig="
  app:
    secure: "dVRdHM/Yeo7H3T4VHDTw0DKw4RZE1B/1jEGGcIWWOTXXH1eBqFNVnykfCLbde3S4OzvKJ15zngL+ab+6SbSPtR7i8+xqwQtBfqkIBiDDxlbR3i8BnY/BgGLp+BfWJp8a578qO3jcaIKLkMRsfivxA9Il2EYSr6guh14X1mgUWzs="
