language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  app:
    secure: LbWodAvmlTt5QMg8bnc/fr6D7XLkwG7vhvC0TCuoJQ20qc3RH2wGIs/sauVJ1pKGmMVrSSXkDGt9272pVQ+5hwUgfSkeJOb7zbySHEutaYDhqrPHGQ8KJrxUhPqbvmVgCijI/Gssli+9NQ008nQvVKiq1cCCLB1x0R69ab5PhOo=
  api_key:
    secure: U0cMMarXogMhLaSWvMhSeOW2LeT5fCsk4ESF9B4DOfc4GgmgkJT4BMqmSqqionr67pLMFE59eR6j7ZvC8AAHj7DIeRiGCU0O9jumIj7aJc0QS/pK6BGB3/T1Fln/+Hn/bvsskOkujzfGiVAgcU/3J2T/AzSjDmCY08PiulSPQGA=
